/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : IIC.h
**     Project     : inter integrate circuit
**     Processor   : MC9S08QE8CLC
**     Component   : Init_IIC
**     Version     : Component 01.081, Driver 01.20, CPU db: 3.00.049
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2017-12-04, 17:27, # CodeGen: 1
**     Abstract    :
**          This file implements the IIC (IIC) module initialization
**          according to the Peripheral Initialization Component settings, and defines
**          interrupt service routines prototypes.
**          The inter-integrated circuit (IIC) interface is a two wire, bidirectional 
**          serial bus which provides a simple, efficient way for data exchange between 
**          devices. The interface is designed for internal serial communication between
**          the MCU and other IIC devices.
**     Settings    :
**          Component name                                 : IIC
**          Device                                         : IIC
**          Settings                                       : 
**          Clock settings                                 : 
**          Multiplier Factor                              : 1
**          Clock rate                                     : 0
**          SCL frequency                                  : 209.715 kHz
**          SDA Hold                                       : 1.669 us
**          Address                                        : 0
**          Transfer direction                             : Transmit
**          Transmit Acknowledge                           : yes
**          Pins                                           : 
**          SDA pin                                        : PTA2_KBIP2_SDA_ADP2
**          SDA pin signal                                 : 
**          SCL pin                                        : PTA3_KBIP3_SCL_ADP3
**          SCL pin signal                                 : 
**          Interrupts                                     : 
**          Interrupt                                      : Viic
**          IIC interrupt                                  : Disabled
**          ISR name                                       : 
**          Initialization                                 : 
**          Call Init method                               : yes
**          Module Enable                                  : yes
**     Contents    :
**         Init - void IIC_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file IIC.h
** @version 01.20
** @brief
**          This file implements the IIC (IIC) module initialization
**          according to the Peripheral Initialization Component settings, and defines
**          interrupt service routines prototypes.
**          The inter-integrated circuit (IIC) interface is a two wire, bidirectional 
**          serial bus which provides a simple, efficient way for data exchange between 
**          devices. The interface is designed for internal serial communication between
**          the MCU and other IIC devices.
*/         
/*!
**  @addtogroup IIC_module IIC module documentation
**  @{
*/         

#ifndef __IIC
#define __IIC

/* MODULE IIC. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"

void IIC_Init(void);
/*
** ===================================================================
**     Method      :  IIC_Init (component Init_IIC)
**     Description :
**         This method initializes registers of the IIC module
**         according to this Peripheral Initialization Component settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END IIC. */

#endif /* ifndef __IIC */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
